tests provided
EnrikeM/7sprint pull request #1
Opened 2024-04-19 09:12 UTC by EnrikeM

2024-04-19 23:58 UTC, dirtymew requested changes
Привет Энрике

хорошая работа - отличное readme тесткейсы описаны верно

но нужно доделать - неверно оформил по файлам

2024-04-19 23:58 UTC, dirtymew commented on main_test.go
> +package main
тут неверно сделал - в  go код и тесты пишутся в разных файлах

например код в main.go тесты на него в main_test.go

2024-04-19 23:58 UTC, dirtymew commented on main_test.go
> +	assert.NotEmpty(t, responseRecorder.Body)
тут хорошо использовать функции  testify

2024-04-19 23:58 UTC, dirtymew commented on main_test.go
> +	assert.Equal(t, responseRecorder.Code, http.StatusOK)
тут лучше require и перед получение body -  так как дальше нет смысла что делать если код неверный

2024-04-20 16:16 UTC, EnrikeM commented on main_test.go
> +	assert.NotEmpty(t, responseRecorder.Body)
Не совсем понял, вместо чего следует использовать функции testify? Вроде бы все тесты сделаны именно с использованием этой библиотеки

2024-04-20 18:39 UTC, dirtymew approved these changes
Энрике 

отличная работа - зачет

2024-04-20 18:39 UTC, dirtymew commented on main_test.go
> +	assert.NotEmpty(t, responseRecorder.Body)
*использовал - прошу прощения)) тут все ок - наоборот хотел отменить удачное решение

2024-04-20 19:17 UTC, merged